import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider, useAuth } from "@/contexts/AuthContext";
import ProtectedRoute from "@/components/ui/ProtectedRoutes";
import Navbar from "@/components/ui/Navbar";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const { user } = useAuth();
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Navbar/>
        <ProtectedRoute>
          <Toaster />
          {children}
        </ProtectedRoute>
        </AuthProvider>
      </body>
    </html>
  );
}
